name: appdesarrollo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  dio: ^5.4.1
  http_parser: ^4.0.2
  path: ^1.8.0
  logger: ^2.0.2+1
  badges: ^3.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^11.4.0
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  location: ^8.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  geolocator: ^13.0.2

flutter:
  uses-material-design: true